### ISSUE TITLE
Workflow to WASM?

### ISSUE THREAD

**Issue by fire** [erlscripten/erlscripten#47]
Is there a workflow to wasm? 

Curious. For science!

**Comment by radrow** [comment]
Not sure what do you mean by "workflow to wasm", but this project targets only transpilation of Erlang into Purescript exclusively. So the final point is whatever PS compiles to (in the current state, JavaScript). We consider taking advantage of WASM for NIF compilation however.

**Comment by fire** [comment]
Does Purescript compile to wasm without embedding a Javascript runtime?

I was curious. I think my question was resolved.
